// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwS02xGy3FUy0A2X_c6LigXX3INBTzQRQ',
    appId: '1:373984599562:web:5773b7818b705a0ebf09f3',
    messagingSenderId: '373984599562',
    projectId: 'kokoro-relationship-meetings',
    authDomain: 'kokoro-relationship-meetings.firebaseapp.com',
    storageBucket: 'kokoro-relationship-meetings.appspot.com',
    measurementId: 'G-WLVYRXZY79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe_tKHxLelcxjn6y5GF1jq5a9WGn5Acu4',
    appId: '1:373984599562:android:97712864b52b0517bf09f3',
    messagingSenderId: '373984599562',
    projectId: 'kokoro-relationship-meetings',
    storageBucket: 'kokoro-relationship-meetings.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgyXHqud4u8adwyHVZVMb7RPDa4-ZylgU',
    appId: '1:373984599562:ios:217e29d02f7d235dbf09f3',
    messagingSenderId: '373984599562',
    projectId: 'kokoro-relationship-meetings',
    storageBucket: 'kokoro-relationship-meetings.appspot.com',
    androidClientId: '373984599562-odv9h676ej58m4dfe0ftcdf3rnu9ihn7.apps.googleusercontent.com',
    iosClientId: '373984599562-5clrco6q2j9kq96ja96kbm3ubht34jso.apps.googleusercontent.com',
    iosBundleId: 'com.jiaxen.kokoro',
  );
}
